### ISSUE TITLE
Error processing EMS data: class AttributeError

### ISSUE THREAD

**Issue by michal-rybinski** [britkat1980/giv_tcp#426]
GivTCP v3.0.4/v3.1.6/v.3.2
EMS firmware: A0.1036
GIV AC3 & 1 battery
GIV AC3 & 1 battery
All 3 configured in config

Hi,
Two days ago I stopped receiving data from EMS (although data from both AC3 inverters is still flowing) and started seeing the following error when starting GivTCP (using docker compose file)

`GivTCP-1  | 2025-10-08 21:02:05,523 - EMS - read        -  [INFO    ] - Starting watch_plant loop...
GivTCP-1  | 2025-10-08 21:02:05,524 - EMS - GivLUT      -  [CRITICAL] - Opening Modbus Connection to 10.100.2.15
GivTCP-1  | 2025-10-08 21:02:05,535 - EMS - read        -  [CRITICAL] - Detecting inverter characteristics...
GivTCP-1  | 2025-10-08 21:02:09,550 - EMS - read        -  [ERROR   ] - Error processing EMS data: ((<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'isoformat'"), <traceback object at 0x7f15d393bc00>), 1435)
GivTCP-1  | 2025-10-08 21:02:09,550 - EMS - read        -  [ERROR   ] - inverter Update failed so using last known good data from cache: ((<class 'Exception'>, Exception('Process Data Failure'), <traceback object at 0x7f15d3938300>), 1949)
GivTCP-1  | 2025-10-08 21:02:09,551 - EMS - read        -  [ERROR   ] - runAll2 Error processing registers: ('KeyError', 'read.py', 2130)
GivTCP-1  | 2025-10-08 21:02:40,652 - EMS - read        -  [ERROR   ] - Error processing EMS data: ((<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'isoformat'"), <traceback object at 0x7f15d393bf00>), 1435)
GivTCP-1  | 2025-10-08 21:02:40,652 - EMS - read        -  [ERROR   ] - inverter Update failed so using last known good data from cache: ((<class 'Exception'>, Exception('Process Data Failure'), <traceback object at 0x7f15d3938c80>), 1949)
GivTCP-1  | 2025-10-08 21:02:40,652 - EMS - read        -  [ERROR   ] - runAll2 Error processing registers: ('KeyError', 'read.py', 2130)
GivTCP-1  | 2025-10-08 21:03:11,754 - EMS - read        -  [ERROR   ] - Error processing EMS data: ((<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'isoformat'"), <traceback object at 0x7f15d3938240>), 1435)
GivTCP-1  | 2025-10-08 21:03:11,754 - EMS - read        -  [ERROR   ] - inverter Update failed so using last known good data from cache: ((<class 'Exception'>, Exception('Process Data Failure'), <traceback object at 0x7f15d393ad40>), 1949)
GivTCP-1  | 2025-10-08 21:03:11,755 - EMS - read        -  [ERROR   ] - runAll2 Error processing registers: ('KeyError', 'read.py', 2130)
Gracefully stopping... (press Ctrl+C again to force)`

At the time I was running v3.0.4 but since upgraded to v3.2 and also downgraded to v3.1.6 but with same results.

I am not sure what I can do, I can see data for EMS not appearing in the MQTT queues and obviously restarting container does not help.

Thanks,
Michal

**Comment by michal-rybinski** [comment]
ok, thanks
