### ISSUE TITLE
Attribute error DEV 3.5.15

### ISSUE THREAD

**Issue by sjs-1956** [britkat1980/giv_tcp#514]
Same error as DEV 3.5.12 in previous issue (500)
<details><summary>Details</summary>
<p>
2026-04-15 10:05:32,487 - GivTCP - read        -  [ERROR   ] - AttributeError: 'NoneType' object has no attribute 'to_bytes'
2026-04-15 10:05:32,488 - GivTCP - read        -  [ERROR   ] - Error in inital detect/refresh: ('AttributeError', 'read.py', 82)
2026-04-15 10:05:32,490 - GivTCP - read        -  [INFO    ] - Starting watch_plant loop...
2026-04-15 10:05:32,490 - GivTCP - GivLUT      -  [CRITICAL] - Opening Modbus Connection to 192.168.1.193
2026-04-15 10:05:32,493 - GivTCP - read        -  [CRITICAL] - Detecting inverter characteristics...
2026-04-15 10:05:34,128 - GivTCP - read        -  [ERROR   ] - AttributeError: 'NoneType' object has no attribute 'to_bytes'
2026-04-15 10:05:34,129 - GivTCP - read        -  [ERROR   ] - Error in inital detect/refresh: ('AttributeError', 'read.py', 82)
2026-04-15 10:05:34,131 - GivTCP - read        -  [INFO    ] - Starting watch_plant loop...
2026-04-15 10:05:34,132 - GivTCP - GivLUT      -  [CRITICAL] - Opening Modbus Connection to 192.168.1.193
2026-04-15 10:05:34,135 - GivTCP - read        -  [CRITICAL] - Detecting inverter characteristics...
2026-04-15 10:05:35,778 - GivTCP - read        -  [ERROR   ] - AttributeError: 'NoneType' object has no attribute 'to_bytes'
2026-04-15 10:05:35,779 - GivTCP - read        -  [ERROR   ] - Error in inital detect/refresh: ('AttributeError', '

</p>
</details>

**Comment by rjenx** [comment]
I am experiencing similar error, this occurred after I updated battery firmware to 3022. I have tried Dev  (3.5.17)  / Beta (3.3.15) and Main  (3.5) versions with the same error messages occurring soon after start. 

HA Version
Installation method  Home Assistant OS
Core 2026.4.3
Supervisor 2026.04.0
Operating System 17.2
Frontend 20260325.7

Inverter Model GIV-AC3.0
Software Version D0.212-A0.212

```
 [DEBUG   ] - Building battery output: 
2026-04-18 12:43:22,421 - GivTCP - read        -  [ERROR   ] - TypeError: 'NoneType' object is not subscriptable
2026-04-18 12:43:22,421 - GivTCP - read        -  [ERROR   ] - Error getting Battery Data: ('TypeError', 'read.py', 389)
2026-04-18 12:43:22,422 - GivTCP - read        -  [ERROR   ] - TypeError: 'NoneType' object is not iterable
2026-04-18 12:43:22,422 - GivTCP - read        -  [ERROR   ] - Error processing Inverter data: ('TypeError', 'read.py', 1313)
2026-04-18 12:43:22,422 - GivTCP - read        -  [ERROR   ] - inverter Update failed so using last known good data from cache: (Exception: Process Data Failure - 1998)
2026-04-18 12:43:22,423 - GivTCP - read        -  [DEBUG   ] - processData result: processData Error processing registers: Process Data Failure
2026-04-18 12:43:22,423 - GivTCP - read        -  [DEBUG   ] - Running pubFromPickle
2026-04-18 12:43:22,423 - GivTCP - read        -  [ERROR   ] - Key Error getting Battery Data: Missing key 'multi_output'
2026-04-18 12:43:22,423 - GivTCP - read        -  [ERROR   ] - Error in calling handler: cannot access local variable 'multi_output' where it is not associated with a value
```
Issues seem to be resolved, identified an error in the 2nd battery which meant it shutdown. Once that was resolved the integration has worked properly ever since. 

No further actions required.
