### ISSUE TITLE
Solar forecast automation error after update to 2.4 

### ISSUE THREAD

**Issue by BondBug** [britkat1980/giv_tcp#132]
I am getting this error message on Home Assistant running on Raspberry Pi and also the same error running Home Assistant on MAC under a Linux virtual machine when trying to run Solar Automation Forecast using the same settings as I used on version 2.3.3

Traceback (most recent call last):
  File "/app/GivTCP_1/palm_soc.py", line 4, in <module>
    import palm_settings as stgs
  File "/app/GivTCP_1/palm_settings.py", line 26, in <module>
    class GE:
  File "/app/GivTCP_1/palm_settings.py", line 100, in GE
    tmp_load_hist_weight = str(GiV_Settings.LOAD_HIST_WEIGHT)
AttributeError: type object 'GiV_Settings' has no attribute 'LOAD_HIST_WEIGHT'

Regards
David Evans

**Comment by BondBug** [comment]
Forgot to say it is a GEN 1 AC Inverter
